name: 'Jekyll Action (Updated)'
description: 'A GitHub Action to build Jekyll sites, forked from https://github.com/lemonarc/jekyll-action'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'grid'
  color: 'red'
